### ISSUE TITLE
Nuxt 3 build errors

### ISSUE THREAD

**Issue by modbender** [bradstiff/app-location#1]
Hello, I'm using Nuxt 3 and am using this inside `utils`

The script is something like this:

```js
import * as Yup from "yup";
import Location from "app-location";

export const urls = {
  Home: ["/"],
  Search: ["/search"],
  Stats: ["/stats"],
  Support: ["/support"],
  Changelog: ["/changelog"],
  About: ["/about"],

  BookList: ["/book"],
  Book: ["/book/:id", { id: Yup.string().required() }],

  Chapter: ["/chapter/:id", { id: Yup.string().required() }],

  PersonList: ["/person"],
  Person: ["/person/:id", { id: Yup.string().required() }],

  GenreList: ["/genre"],
  Genre: ["/genre/:id", { id: Yup.string().required() }],

  UserList: ["/user"],
  User: ["/user/:id", { id: Yup.string().required() }],
  UserSettings: ["/settings"],

  //   Auth pages
  Signin: ["/signin"],
  Signup: ["/signup"],
  Logout: ["/signout"],
};

for (let url in urls) urls[url] = new Location(...urls[url]);
```

By doing this in the app I can use it like `urls.BookList.path` and such.

But when building I get the error:

```cmd
[nuxt] [request error] [unhandled] [500] Location is not a constructor
  at /E:/Project/js/vue/site-js/.output/server/chunks/server.mjs:3575:15
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
  at async /E:/Project/js/vue/site-js/.output/server/chunks/renderer.mjs:317:24
  at async /E:/Project/js/vue/site-js/.output/server/chunks/renderer.mjs:404:64
  at async /E:/Project/js/vue/site-js/.output/server/chunks/renderer.mjs:34:22
  at async Object.handler (/E:/Project/js/vue/site-js/.output/server/node_modules/h3/dist/index.mjs:1196:19)
  at async Server.toNodeHandle (/E:/Project/js/vue/site-js/.output/server/node_modules/h3/dist/index.mjs:1271:7)
```

This happens when it comes to prerendering. Either way I get this error even after testing deployment. All the pages are 500 because of this error.
Any idea on this error?

**Comment by modbender** [comment]
Adding
```js
  build: {
    transpile: ["app-location"],
  },
```
Seems to fixed the issue for now.
